#!/bin/sh
#
# /etc/rc.d/lactd: start/stop LACT daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/bin/lact
PIDFILE=/run/lactd.pid
LOGFILE=/var/log/lact.log
OPTS="daemon"

case $1 in
start)
    $SSD --start --background --make-pidfile --pidfile=$PIDFILE --output $LOGFILE --exec $PROG -- $OPTS
    ;;
stop)
    $SSD --stop --remove-pidfile --pidfile=$PIDFILE --retry 10
    ;;
restart)
    $0 stop
    $0 start
    ;;
status)
    $SSD --status --exec $PROG
    case $? in
    0) echo "$PROG is running with pid $(cat ${PIDFILE})" ;;
    1) echo "$PROG is not running but the pid file $PID exists" ;;
    3) echo "$PROG is not running" ;;
    4) echo "Unable to determine the program status" ;;
    esac
    ;;
*)
    echo "usage: $0 [start|stop|restart|status]"
    ;;
esac

# End of file
